version: "3.0"
services:
  redis:
    image: docker.io/redis:8-alpine
    restart: always
    networks:
      - aggregator
  db:
    image: docker.io/mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret
      - MARIADB_DATABASE=aggregator
      - MARIADB_USER=aggregator
      - MARIADB_PASSWORD=secret
    networks:
      - aggregator

  aggregator:
    image: ghcr.io/adarshahd/aggregator:master
    depends_on:
      - db
    volumes:
      - ./.env:/var/www/html/.env:rw,z
    ports:
      - 8000:8000
    networks:
      - aggregator

  queue:
    depends_on:
      - aggregator
    image: ghcr.io/adarshahd/aggregator:master
    volumes:
      - ./.env:/var/www/html/.env:rw,z
    command: /usr/bin/supervisord -c /etc/supervisord.d/laravel-queue.ini

  scheduler:
    depends_on:
      - aggregator
    image: ghcr.io/adarshahd/aggregator:master
    volumes:
      - ./.env:/var/www/html/.env:rw,z
    command: /usr/bin/supervisord -c /etc/supervisord.d/laravel-scheduler.ini

networks:
  aggregator:
