on:
  push:
  workflow_dispatch:

name: Run Application Tests
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "PHP setup"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, gd

      - name: "Install dependencies & Setup environment"
        run: |
          composer install --prefer-dist
          cp .env.example .env
          php artisan key:generate --force
      - name: "Run Tests"
        run: |
          php artisan test
